language: node_js

node_js:
  - 11
  - 10

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

script:
  - npm run test
  - npm run ban -- --all

after_success:
  - npm run report-coverage

notifications:
  email:
    recipients:
      - xiechao06@gmail.com
